name: Build aria2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: aria2/aria2
    - name: Install dependencies
      run: |
        brew install automake
    - name: Prepare
      run: autoreconf -i
    - name: configure
      run: ./configure ARIA2_STATIC=yes --without-appletls --with-openssl --disable-shared --enable-static
    - name: make
      run: make -j$(nproc)
    - name: check binary
      run: ./src/aria2c --help
