name: Build aria2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: aria2/aria2
    - name: Install dependencies
      run: |
        brew install automake
    - name: Prepare
      run: autoreconf -i
    - name: configure
      run: ./configure ARIA2_STATIC=yes --with-openssl --disable-shared --enable-static --without-gnutls
    - name: make
      run: make -j$(nproc)
    - name: zip
      run: |
        cp src/aria2c .
        zip -D aria2-darwin-amd64.zip aria2c
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: aria2-darwin-amd64.zip
